### PR TITLE
Add Google Colab Notebooks as a valid modules

### PR DESCRIPTION
**Pull request by panaali**

### CODE REVIEW

**Comment by yuvipanda** [comment]
Heya! Thanks for the PR :) Can you  provide some more information about what's going on? Does colab not provide standard metadata fields?

**Comment by Carreau** [comment]
cc @jakevdp also maybe ? 

I'm guessing colab also support multiple languages, so this would not make sens to run if it was not Python. If that's really how you set languages, I guess we can get that in, but it woudl be nice to have something generic that distinguish languages from frontends .

**Comment by jakevdp** [comment]
cc/ @colaboratory-team

**Comment by jakevdp** [comment]
As of several months ago, Colab puts a standard Python kernelspec into every saved notebook, although notebooks created before then and not modified since may be missing this field.

I'm curious in what context you ran into the issue that prompted this change?

**Comment by panaali** [comment]
@jakevdp  Thanks for your consideration. I faced this issue when I wanted to use **ipynb** in Google Colaboratory. 
I just created a new notebook in colab. The fields in _kernelspec_ do not have the language field so we can not import a notebook that is created using colab.
`
{
  "nbformat": 4,
  "nbformat_minor": 0,
  "metadata": {
    "colab": {
      "name": "Untitled4.ipynb",
      "version": "0.3.2",
      "provenance": []
    },
    "kernelspec": {
      "name": "python2",
      "display_name": "Python 2"
    }
  },
  "cells": [...]
}
`
I also think that this pull request is not a generalized solution.

**Comment by jakevdp** [comment]
H @panaali - according to the [nbformat 4 schema](https://github.com/jupyter/nbformat/blob/master/nbformat/v4/nbformat.v4.schema.json) the only required entries in the kernelspec metadata are ``"name"`` and ``"display_name"``, which do appear in the schema you pasted here.

Can you give a more specific example of the issue you encountered?

**Comment by panaali** [comment]
@jakevdp If `language` is not a required filed in nbformat 4 schema, I guess the way [utils.py:37](https://github.com/ipython/ipynb/blob/0fbc924bf06584653571b5d6a4be133a3d3559a6/ipynb/utils.py#L37) validate the ipynb file is not correct, since it looks for a `language` field which Colab generated notebooks does not have.

If you download a Colab generated notebook, and try to import it using `ipynb` module, you will get this error:
Screen Shot 2019-04-09 at 11 26 25 AM

**Comment by jakevdp** [comment]
Yes, I think you're right. It would be useful for the ipynb package to only require fields that are specified as required by the nbformat schema.

**Comment by panaali** [comment]
@Carreau What do you think about this? How should the [utils.py:37](https://github.com/ipython/ipynb/blob/0fbc924bf06584653571b5d6a4be133a3d3559a6/ipynb/utils.py#L37) validate the language then?

**Comment by Carreau** [comment]
There are many updates to this project that would be nice. There are also a number of similar projects arounds. The most recent one I've heard of bing https://github.com/ReviewNB/treon , (have looked in the code though). It would be nice to wrangle them all into a one well-documenting and working framework. 

Now there is the philosophical question; do we _want_ to be able to import notebooks. This one  is a bit unclear. 

I'd love to push all of these discussions forward, but unfortunately my time is limited and $DAYJOB is not spending as much time as I'd like on Jupyter; so I'm happy to delegate.

**Comment by yuvipanda** [comment]
@jakevdp @panaali It checks for the field because I wanna make sure we only try to import notebooks we can - which is specifically python3 notebooks. The kernel name field isn't reliable, since kernels can really be called anything - conda for example puts environment names in them. This is why we need the extra field there.

**Comment by panaali** [comment]
@yuvipanda You're right but the `language` field is not a required field in [nbformat 4 schema](https://github.com/jupyter/nbformat/blob/master/nbformat/v4/nbformat.v4.schema.json), so we shouldn't rely on that. I don't know what would be the solution in here.

**Comment by jakevdp** [comment]
Maybe use the language field if present, otherwise fall back to something like ``"python" in kernel_spec['name'].lower()``, otherwise fail?

**Comment by jakevdp** [comment]
That would solve the problem in the Colab case, as well as generalizing to others. You'll still miss notebooks that specify no language and have kernels like ``"conda-env-py37"``, but it's probably better than nothing.

**Pull request closed without merging**
